### ISSUE TITLE
Try to find ways to tweak performance on appspot

### ISSUE THREAD

**Issue by pablotanner** [sopra-fs23-group-13/meme-it-client#100]
So it runs smoother and doesn't close down lobbies randomly.

Might work by already calling backend on homepage so instances are started earlier?

**Comment by pablotanner** [comment]
Some of the issues that occur consistently are:
- On cold start, lobby creation takes ages and often closes down the lobby (starts working perfectly fine after server is properly started)
- After you start the game from the lobby, it displays the spinner (maybe infinitely or until the creation phase ends) until you reload the page

**Comment by Cnordg** [comment]
Check issue on server branch; we might run 1 instance constantly (but it might become bloated with data so we need to do a refresh before our presentation). We can also temporarily up the instance specs to F3 or F4 to have more ram and cpu resources
