### ISSUE TITLE
fix bug so that you can have more than 4 lobbies in the list with no error

### ISSUE THREAD

**Issue by weberlii** [sopra-fs23-group-13/meme-it-client#145]

**Comment by weberlii** [comment]
see beta testing feedback

**Comment by danielLutziger** [comment]
not sure whether this is still a bug, will definitely need some more in depth testing

**Comment by pablotanner** [comment]
> not sure whether this is still a bug, will definitely need some more in depth testing

also for some reason the home page gets horizontal slidebars if there's more than 4 lobbies in the lobby list which is weird

**Comment by danielLutziger** [comment]
not sure what you mean
![image](https://github.com/sopra-fs23-group-13/meme-it-client/assets/10813124/9bbc52b7-fcd6-4504-b8b8-c87d8a6588de)

maybe the table is too big and we have to reduce the size such that there  won't be a scrollbar.

**Comment by danielLutziger** [comment]
(just realized one cannot see, but there is no scrollbar on my screen except this one to browse the lobbies)

but the white container is massive.

**Comment by pablotanner** [comment]
Yeah you are right, just tested it and for some reason it's working perfectly fine now lol

**Comment by danielLutziger** [comment]
Jup I did some changes yesterday

**Comment by danielLutziger** [comment]
https://github.com/sopra-fs23-group-13/meme-it-client/pull/158
