### ISSUE TITLE
do not fetch new meme when reloading page

### ISSUE THREAD

**Issue by danielLutziger** [sopra-fs23-group-13/meme-it-client#148]

**Comment by danielLutziger** [comment]
I guess we could make a frontend task out of it... or at least we can just quick fix it here

**Comment by Cnordg** [comment]
I don’t understand the issue as it seems like a frontend task. Can you explain?

On 15 May 2023, at 22:31, daniel ***@***.***> wrote:

﻿

I guess we could make a frontend task out of it... or at least we can just quick fix it here
