### ISSUE TITLE
Possible to add text outside of memes

### ISSUE THREAD

**Issue by pablotanner** [sopra-fs23-group-13/meme-it-client#152]
This is caused by the background boxes which don't rescale automatically if you increase the font size. This leads to overly large boxes and if placed at an edge can put the text outside of the meme.

**Step by Step:**
Enter Text
<img src="https://github.com/sopra-fs23-group-13/meme-it-client/assets/15524263/f2d7ab20-4820-4d63-bc71-473172c3ac02" width="400" height="400"/>

Enlarge Text
<img src="https://github.com/sopra-fs23-group-13/meme-it-client/assets/15524263/4eb92e6e-d9a8-4eca-be53-e1e337c6abb9" width="400" height="400"/>

Move to Edge (Only to get text out of meme, textbox will be very large anyways)
<img src="https://github.com/sopra-fs23-group-13/meme-it-client/assets/15524263/3fd19844-aba1-4e83-9e2b-b65905778953" width="400" height="400"/>

Result
<img src="https://github.com/sopra-fs23-group-13/meme-it-client/assets/15524263/b10c0159-cc1b-4676-a854-19694d525a1d" width="400" height="400"/>

**Comment by danielLutziger** [comment]
updated version

**Comment by danielLutziger** [comment]
closed by https://github.com/sopra-fs23-group-13/meme-it-client/commit/14c55c6645135b829cd46e22ca5b03b86b7048e2
