### ISSUE TITLE
Textbox not shown in GameRating

### ISSUE THREAD

**Issue by pablotanner** [sopra-fs23-group-13/meme-it-client#159]
The textboxes are sometimes not shown for some memes (or just the background is shown) in the GameRating phase, even though they have been saved (since they do work in the leaderboard afterwards)

**Comment by pablotanner** [comment]
Only renders textboxes on first slide (unless you recompile then the textboxes on the slide you are on will be the ones working) so maybe carousel needs to rerender components when you switch slides?

**Comment by danielLutziger** [comment]
fixed with https://github.com/sopra-fs23-group-13/meme-it-client/commit/ab88980322d195905da6a0d23e404f974a30ec37
