### ISSUE TITLE
Images not shown in proper dimensions

### ISSUE THREAD

**Issue by Cnordg** [sopra-fs23-group-13/meme-it-client#166]
<img width="714" alt="Screenshot 2023-05-23 at 15 13 28" src="https://github.com/sopra-fs23-group-13/meme-it-client/assets/91025733/5f8274f6-d923-40d9-8daa-83d16a3d9767">

Note: im using safari in private tab (might not be a problem on chrome or Firefox)

**Comment by pablotanner** [comment]
@Cnordg We are putting all templates/memes into 400x400 on purpose, I forgot why though😅

**Comment by Cnordg** [comment]
We should probably change that at least during meme creation and voting as we have the full screen available and the compressed meme doesn’t look nice. For round and game results we probably will need to unify the format somehow..


On 23 May 2023, at 20:09, Pablo Tanner ***@***.***> wrote:

﻿

@Cnordg<https://github.com/Cnordg> We are putting all templates/memes into 400x400 on purpose, I forgot why though😅

**Comment by pablotanner** [comment]
@Cnordg I agree that it would look better but changing it would bring a lot of issues and I wouldn't risk f'ing anything up when the deadline is this close :/

**Comment by Cnordg** [comment]
This is my personal opinion; but to me it looks quite bad and makes the game less enjoyable. I will take a look tomorrow to see what impact it would have to change it as I really think this should be done

On 23 May 2023, at 21:04, Pablo Tanner ***@***.***> wrote:

﻿

@Cnordg<https://github.com/Cnordg> I agree that it would look better but changing it would bring a lot of issues and I wouldn't risk f'ing anything up when the deadline is this close :/

**Comment by danielLutziger** [comment]
Would have been nice to be advised earlier with that bug as it has always been the case.

A reason for the 400x400 viewbox is that the memes come in different resolutions. Some come in 2kx2k and this stuff. i tried scaling them down to a min height / min width depending if it was a horinzontal / vertical meme. it did not work properly and thus I sticked with it.

**Comment by Cnordg** [comment]
I can take a look at it

**Comment by Cnordg** [comment]
I have fixed this, now the only problem remains is that the text boxes dont show properly initially. I will fix and push to this branch :))

**Comment by Cnordg** [comment]
Apparently it creates new issues on edge and Firefox where you can't type into text box and/or text box bounces around @danielLutziger

**Comment by danielLutziger** [comment]
https://github.com/sopra-fs23-group-13/meme-it-client/pull/176
