### ISSUE TITLE
Unable to swap memes if user sets meme change limit without changing any other parameter

### ISSUE THREAD

**Issue by Cnordg** [sopra-fs23-group-13/meme-it-client#171]
This is a bit of a weird one, I assume it has something to do with how the state is updated. If I change the limit duration then I have the ability to swap memes in game otherwise (if I dont change any param apart from swap limit) its greyed out.

Note: Im using chrome

**Comment by Cnordg** [comment]
Yeah the user has to edit the voting time (on lobby settings) AFTER he/she changes the meme swap limit, otherwise it's not possible to swap memes in the game. I can do demo if you want to hop on a call

**Comment by danielLutziger** [comment]
yes pls

**Comment by Cnordg** [comment]
Only if setting 10 selected (lets just remove it as Daniel suggested)

**Comment by danielLutziger** [comment]
#176
