### ISSUE TITLE
Best meme of the round carousel move title to the top

### ISSUE THREAD

**Issue by Cnordg** [sopra-fs23-group-13/meme-it-client#177]
Two issues;
- There are two rounded containers in red that can be seen
- The red container blocks the view of the meme maybe we add a title above the meme? 

@danielLutziger 

<img width="927" alt="Screenshot 2023-05-24 at 16 29 27" src="https://github.com/sopra-fs23-group-13/meme-it-client/assets/91025733/41d9e68e-f61b-494e-84e3-16409f206645">

**Comment by danielLutziger** [comment]
we could remove the background or make the headline smaller

**Comment by Cnordg** [comment]
Can we not move title up higher so it doesnt cover meme at all? then we can make it bold and not have the double containers

**Comment by danielLutziger** [comment]
I made the text smaller, bug cannot get it out of the image. the user has in the slide show all the information and can in the table, if he wants to  see it look at it in more detail again by clicking on it

**Comment by danielLutziger** [comment]
closes the issue. perfect solution, thanks
