### ISSUE TITLE
Increase contrast in tutorial

### ISSUE THREAD

**Issue by Cnordg** [sopra-fs23-group-13/meme-it-client#178]
Maybe we need to change the background color to make it clash less with the background and to make the text more readable. What do you think? @danielLutziger 

<img width="857" alt="Screenshot 2023-05-24 at 16 33 34" src="https://github.com/sopra-fs23-group-13/meme-it-client/assets/91025733/7898a8ce-3da6-434d-b610-8673c5626d51">

**Comment by danielLutziger** [comment]
I played around a little bit with the color, but agree. I went for a kinda readable color but not really... whatcolor do you have in mind?

**Comment by Cnordg** [comment]
Maybe we make it less transparent or we make it the same color as the tutorial header (the whitish solid part) that way it stands out.

**Comment by danielLutziger** [comment]
pr #176
