### ISSUE TITLE
As a user, I want to be able to see a lobby's game settings before the game starts and also be able to exit the lobby/game at any point.

### ISSUE THREAD

**Issue by danielLutziger** [sopra-fs23-group-13/meme-it-client#52]
## Acceptance criteria

- [ ] sopra-fs23-group-13/meme-it-client#51
- [ ] sopra-fs23-group-13/meme-it-client#50

## Tests

- [ ] Player list and player count should be updated instantly when a player leaves. 
- [ ] If a player leaves during a game, memes that they already submitted should still be displayed but the game should deal with any absent players for future rounds.
- [ ] If the lobby creator leaves the game after it has started, other players should remain unaffected.
- [ ] If every player except for one leaves the lobby, the game should finish with the remaining player as winner.

**Comment by pablotanner** [comment]
https://github.com/sopra-fs23-group-13/meme-it-client/commit/15d72e71be3953cf03cfc256a4ab0dff36fbfb69
