### ISSUE TITLE
[F] The lobby creator should be allowed to kick people out of the lobby before the game starts

### ISSUE THREAD

**Issue by pablotanner** [sopra-fs23-group-13/meme-it-client#61]

**Comment by danielLutziger** [comment]
#65

**Comment by pablotanner** [comment]
Kick feature implementation is temporary fix, might have to be changed if changes in backend occur
https://github.com/sopra-fs23-group-13/meme-it-client/commit/00b216dc0b65033d5fb56fb0124f35f09d41f906
