### ISSUE TITLE
"Private" switch in Lobby settings behaving weirdly 

### ISSUE THREAD

**Issue by pablotanner** [sopra-fs23-group-13/meme-it-client#64]
If you update lobby without touching Private switch it sets lobby to private, other times works fine.

**Comment by danielLutziger** [comment]
fixed in https://github.com/sopra-fs23-group-13/meme-it-client/pull/65

**Comment by pablotanner** [comment]
was still broken but now fixed in https://github.com/sopra-fs23-group-13/meme-it-client/pull/66/commits/8b5e9fe09b8d0d5525c1343b367b7dcddd51048f
